package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

type fileEntry struct {
	Path string
	Data []byte
}

func main() {
	dir := flag.String("dir", "", "Directory to pack as static resources")
	out := flag.String("out", "static_data.go", "Output Go file path")
	pkg := flag.String("pkg", "staticdata", "Package name for output Go file")
	varName := flag.String("var", "StaticData", "Variable name for the map")
	flag.Parse()

	if *dir == "" {
		fmt.Println("Please specify the directory to pack: -dir=/path/to/dir")
		os.Exit(1)
	}

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Printf("Failed to resolve directory: %v\n", err)
		os.Exit(1)
	}

	var files []fileEntry
	err = filepath.Walk(absDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(absDir, path)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		files = append(files, fileEntry{Path: filepath.ToSlash(rel), Data: data})
		return nil
	})
	if err != nil {
		fmt.Printf("Failed to walk directory: %v\n", err)
		os.Exit(1)
	}

	buf := &bytes.Buffer{}
	tmpl := template.Must(template.New("embed").Parse(embedTemplate))
	err = tmpl.Execute(buf, struct {
		Pkg   string
		Var   string
		Files []fileEntry
	}{
		Pkg:   *pkg,
		Var:   *varName,
		Files: files,
	})
	if err != nil {
		fmt.Printf("Failed to render template: %v\n", err)
		os.Exit(1)
	}

	err = os.WriteFile(*out, buf.Bytes(), 0644)
	if err != nil {
		fmt.Printf("Failed to write output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Packing complete: %s -> %s\n", absDir, *out)
}

const embedTemplate = `// Code generated by embedtool. DO NOT EDIT.
package {{.Pkg}}

var {{.Var}} = map[string][]byte{
{{- range .Files}}
	"{{.Path}}": []byte{ {{ range $i, $b := .Data }}{{if $i}}, {{end}}{{printf "%#x" $b}}{{end}} },
{{- end}}
}
`
